### ISSUE TITLE
Ingest.py

### ISSUE THREAD

**Issue by AdiKsOnDev** [AdiKsOnDev/PrivateFalcon#1]
# TODO
---
- [x] Make the `load_document()` function
- [x] Make the `load_directory()` function
- [x] Make a function for splitting the documents in chunk 
- [x] Make a function to split documents into batches that Chroma can process
- [x] Use the above functions to parse the data
